import { AttributeKeys, ControlCommands, ControlKeys } from "../../constants"
import { blockKey, BlockOptions, CMDBlock, CommandLibray, queries, responses } from "../Library"
import { hexFunction } from "./panasonicControlCommands"

const Responses:responses={
    power: { '001': 'On', '000': 'Off' },
    shutter: { '000': 'Open', '001': 'Closed' },
    ip_address: undefined,
    port: undefined,
    auth: undefined,
    make: undefined,
    id: undefined,
    name: undefined
}

const Querys:queries={
    power: 'QPW',
    shutter: 'QSH',
    ip_address: undefined,
    port: undefined,
    auth: undefined,
    make: undefined,
    id: undefined,
    name: undefined
}
const getCMDBlock=(hexCommand: string, attribute: AttributeKeys, options?: BlockOptions ):CMDBlock=>{
    return {
        hexCommand: '00'+hexCommand,
        response: Responses[attribute],
        query: '00'+Querys[attribute],
        range: options?.range,
        dropEqual: options?.dropEqual,
        fixedSize: options?.fixedSize,
        attribute: attribute
       
    }
}
export const PanasonicCommands: CommandLibray={
    [ControlCommands.POWER_ON]: getCMDBlock('PON', AttributeKeys.power),
    [ControlCommands.POWER_OFF]: getCMDBlock('POF', AttributeKeys.power),
    [ControlCommands.SHUTTER_OPEN]: getCMDBlock('OSH:0', AttributeKeys.shutter),
    [ControlCommands.SHUTTER_CLOSED]: getCMDBlock('OSH:1', AttributeKeys.shutter),
    EDGE_BLENDING_OFF: undefined,
    EDGE_BLENDING_ON: undefined,
    EDGE_BLENDING_MARKERS_ON: undefined,
    EDGE_BLENDING_MARKERS_OFF: undefined,
    TEST_PATTERN_OFF: undefined,
    TEST_PATTERN_WHITE: undefined,
    TEST_PATTERN_BLACK: undefined,
    TEST_PATTERN_FOCUS_RED: undefined,
    TEST_PATTERN_FOCUS_WHITE: undefined,
    MENU: undefined,
    MENU_DOWN_KEY: undefined,
    MENU_UP_KEY: undefined,
    MENU_RIGHT_KEY: undefined,
    MENU_LEFT_KEY: undefined,
    MENU_DEFAULT_KEY: undefined,
    MENU_ENTER_KEY: undefined,
    EDGE_BLENDING_UPPER_ON: undefined,
    EDGE_BLENDING_UPPER_OFF: undefined,
    EDGE_BLENDING_LOWER_OFF: undefined,
    EDGE_BLENDING_LOWER_ON: undefined,
    EDGE_BLENDING_RIGHT_OFF: undefined,
    EDGE_BLENDING_RIGHT_ON: undefined,
    EDGE_BLENDING_LEFT_OFF: undefined,
    EDGE_BLENDING_LEFT_ON: undefined,
    OSD_POSITION_UPPER_LEFT: undefined,
    OSD_POSITION_CENTER_LEFT: undefined,
    OSD_POSITION_LOWER_LEFT: undefined,
    OSD_POSITION_TOP_CENTER: undefined,
    OSD_POSITION_CENTER: undefined,
    OSD_POSITION_LOWER_CENTER: undefined,
    OSD_POSITION_UPPER_RIGHT: undefined,
    OSD_POSITION_CENTER_RIGHT: undefined,
    OSD_POSITION_LOWER_RIGHT: undefined,
    PROJECTOR_NAME: undefined,
    NUMBER_KEY_0: undefined,
    NUMBER_KEY_1: undefined,
    NUMBER_KEY_2: undefined,
    NUMBER_KEY_3: undefined,
    NUMBER_KEY_4: undefined,
    NUMBER_KEY_5: undefined,
    NUMBER_KEY_6: undefined,
    NUMBER_KEY_7: undefined,
    NUMBER_KEY_8: undefined,
    NUMBER_KEY_9: undefined,
    LENS_POSTION_HOME: undefined,
    LENS_CALIBRATION: undefined,
    LENS_SHIFT_H_SP: undefined,
    LENS_SHIFT_H_SN: undefined,
    LENS_SHIFT_H_NP: undefined,
    LENS_SHIFT_H_NN: undefined,
    LENS_SHIFT_H_FP: undefined,
    LENS_SHIFT_H_FN: undefined,
    LENS_SHIFT_V_SP: undefined,
    LENS_SHIFT_V_SN: undefined,
    LENS_SHIFT_V_NP: undefined,
    LENS_SHIFT_V_NN: undefined,
    LENS_SHIFT_V_FP: undefined,
    LENS_SHIFT_V_FN: undefined,
    LENS_FOCUS_SP: undefined,
    LENS_FOCUS_SN: undefined,
    LENS_FOCUS_NP: undefined,
    LENS_FOCUS_NN: undefined,
    LENS_FOCUS_FP: undefined,
    LENS_FOCUS_FN: undefined,
    LENS_ZOOM_SP: undefined,
    LENS_ZOOM_SN: undefined,
    LENS_ZOOM_NP: undefined,
    LENS_ZOOM_NN: undefined,
    LENS_ZOOM_FP: undefined,
    LENS_ZOOM_FN: undefined,
    BACK_COLOR_BLUE: undefined,
    BACK_COLOR_BLACK: undefined,
    BACK_COLOR_USER_LOGO: undefined,
    BACK_COLOR_DEFAULT_LOGO: undefined,
    PROJECTOR_ID: undefined,
    OSD_ON: undefined,
    OSD_OFF: undefined,
    FREEZE_OFF: undefined,
    FREEZE_ON: undefined,
    CEILING_MOUNT_ON: undefined,
    CEILING_MOUNT_OFF: undefined,
    STANDBY_MODE_NETWORK: undefined,
    AUTO_SHUTDOWN_OFF: undefined,
    POWER_HOG_ON: undefined,
    INPUT_SELECT_COMPUTER1: undefined,
    INPUT_SELECT_COMPUTER2: undefined,
    INPUT_SELECT_VIDEO: undefined,
    INPUT_SELECT_YC: undefined,
    INPUT_SELECT_DVI: undefined,
    INPUT_SELECT_HDMI1: undefined,
    INPUT_SELECT_HDMI2: undefined,
    INPUT_SELECT_SDI1: undefined,
    INPUT_SELECT_DIGITALLINK: undefined,
    PROJECTOR_INSTALL_METHOD_FRONT_DESK: undefined,
    PROJECTOR_INSTALL_METHOD_REAR_DESK: undefined,
    PROJECTOR_INSTALL_METHOD_FRONT_CEILING: undefined,
    PROJECTOR_INSTALL_METHOD_REAR_CEILING: undefined,
    PROJECTOR_INSTALL_METHOD_FRONT_AUTO: undefined,
    PROJECTOR_INSTALL_METHOD_REAR_AUTO: undefined,
    OSD_ROTATION_OFF: undefined,
    OSD_ROTATION_CLOCKWISE: undefined,
    OSD_ROTATION_COUNTERCLOCKWISE: undefined,
    LIGHT_OUTPUT: undefined
}